name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true  # Ensure LFS is enabled

      - name: Fetch LFS files
        run: git lfs pull

      # Debugging step (remove if unnecessary)
      - name: List tracked LFS files
        run: git lfs ls-files

      # Install FFmpeg
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # Transcode video to H.264 (fix for Unity compatibility)
      - name: Transcode Video to H.264
        run: ffmpeg -i Assets/Resources/Beautiful_002.mp4 -vcodec libx264 -acodec aac Assets/Resources/Beautiful_002_transcoded.mp4

      # Reimport all assets in Unity to ensure proper processing
      - name: Reimport All Assets in Unity
        run: |
          /opt/Unity/Editor/Unity -batchmode -projectPath ${{ github.workspace }} -executeMethod UnityEditor.AssetDatabase.ImportAsset -quit

      - if: ${{ matrix.targetPlatform == 'Android' }}
        uses: jlumbroso/free-disk-space@v1.3.1

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
